// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiLhEMjAU0g6__pcBHuKhNWs4Oo4pcUU',
    appId: '1:215558347573:web:19dc0ed38fa6ff02b58a7c',
    messagingSenderId: '215558347573',
    projectId: 'spelling-game-ae62e',
    authDomain: 'spelling-game-ae62e.firebaseapp.com',
    storageBucket: 'spelling-game-ae62e.firebasestorage.app',
    measurementId: 'G-81EPC37CPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-OhnP5_rojgZqxhp421j1dXn6sCR47c',
    appId: '1:215558347573:android:89066790d3a5349cb58a7c',
    messagingSenderId: '215558347573',
    projectId: 'spelling-game-ae62e',
    storageBucket: 'spelling-game-ae62e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-kKreVTzhnvd96ZqYwKDXEqbm9SF9JKI',
    appId: '1:215558347573:ios:8ce7016c8aa20b22b58a7c',
    messagingSenderId: '215558347573',
    projectId: 'spelling-game-ae62e',
    storageBucket: 'spelling-game-ae62e.firebasestorage.app',
    iosBundleId: 'com.example.spellingGame',
  );
}
